config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'layouts', to: 'home#layouts', as: 'layouts'

  namespace :admins do
    resources :dashboard, only: [:index]
    resources :layouts, only: [:create]

    get 'layout', to: 'dashboard#layout', as: 'layout'
    get 'event_type', to: 'dashboard#event_type', as: 'event_type'
    get 'payment', to: 'dashboard#payment', as: 'payment'
    get 'messages', to: 'dashboard#messages', as: 'messages'

    post 'create_layout', to: 'dashboard#create_layout', as: 'create_layout'
    patch 'update_layout/:id', to: 'dashboard#update_layout', as: 'update_layout'
    put 'update_layout/:id', to: 'dashboard#update_layout'
    get 'layout/:id/edit', to: 'dashboard#edit_layout', as: 'edit_layout'
    delete 'destroy_layout/:id', to: 'dashboard#destroy_layout', as: 'destroy_layout'

    post 'create_event_type', to: 'dashboard#create_event_type', as: 'create_event_type'
    patch 'update_event_type/:id', to: 'dashboard#update_event_type', as: 'update_event_type'
    put 'update_event_type/:id', to: 'dashboard#update_event_type'
    delete 'destroy_event_type/:id', to: 'dashboard#destroy_event_type', as: 'destroy_event_type'

    post 'reply_messages', to: 'dashboard#reply_messages', as: 'reply_messages'
    post 'new_email', to: 'dashboard#new_email', as: 'new_email'
  end

  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :users do
    resources :dashboard, only: [:index]
    resources :events
    resources :cost_managements, only: [:create]
    resources :paypal
    resources :baokim

    devise_scope :user do
      get '/password/send_instructions' => 'passwords#send_instructions_successfull', as: 'send_instructions_successfull'
    end
  end

  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    unlocks: 'users/unlocks',
    omniauth_callbacks: "users/omniauth_callbacks",
    root: "home#index"
  }

  patch 'update_information/:id', to: 'users#update_information', as: 'update_information'
  put 'update_information/:id', to: 'users#update_information'

  post 'new_message', to: 'home#new_message', as: 'new_message'

  patch 'upload_avatar/:id', to: 'users#upload_avatar', as: 'upload_avatar'
  put 'upload_avatar/:id', to: 'users#upload_avatar'

  post 'get_district_ajax', to: 'users#get_district_ajax', as: 'get_district_ajax'
  post 'get_commune_ajax', to: 'users#get_commune_ajax', as: 'get_commune_ajax'
  post 'check_username_ajax', to: 'users#check_username_ajax', as: 'check_username_ajax'
  post 'check_event_slug_ajax', to: 'users/events#check_event_slug_ajax', as: 'check_event_slug_ajax'

  get ':username', to: 'users#show', as: :user

  post "/hook" => "users/paypal#hook"
  post "/baokim" => "users/baokim#create"
end

app/views/admins/contact_message/_contact_message_item.html.erb
<li class="message-item cursor-pointer" data-toggle="modal" data-target="#contactMessageModal<%= contact_message.id %>">
  <div class="table-panel">
    <div class="table-child ver-mid message-id">
      #<%= contact_message.id %>
    </div>
    <div class="table-child ver-mid message-time">
      <%= contact_message.created_at.strftime("%Y %b %d %H:%M") %>
    </div>
    <div class="table-child ver-mid message-email">
      <%= contact_message.email %>
    </div>
    <div class="table-child ver-mid message-name">
      <%= contact_message.name %>
    </div>
    <div class="table-child message-content">
      <%= truncate( contact_message.message , length: 60) %>
    </div>
  </div>
</li>
<div class="modal fade zevent-modal contact-message-modal" id="contactMessageModal<%= contact_message.id %>" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <button type="button" class="close-modal no-outline" data-dismiss="modal">
        <%= image_tag "vendor/close.png" %>
      </button>
      <div class="modal-body text-center">
        <h3 class="modal-title">Contact message from <%= contact_message.name %></h3>
        <div class="contact-message-block">
          <div class="table-panel">
            <div class="table-child label-title">Name</div>
            <div class="table-child"><%= contact_message.name %></div>
          </div>
          <div class="table-panel">
            <div class="table-child label-title">Email</div>
            <div class="table-child"><%= contact_message.email %></div>
          </div>
          <div class="message-content">
            <%= contact_message.message %>
          </div>
        </div>
        <h3 class="modal-title">Reply message</h3>
        <div class="reply-message-block">
          <ul class="list-unstyled reply_message_list js--reply_message_list">
            <% contact_message.reply_messages.order('created_at DESC').each do |reply_message| %>
              <%= render "admins/contact_message/reply_message_item", target: reply_message %>
            <% end %>
          </ul>
        </div>
        <%= render "admins/contact_message/form_reply_email", target: contact_message %>
      </div>
    </div>
  </div>
</div>

app/views/admins/contact_message/_form_new_email.html.erb
<%= form_for(@new_email, url: admins_new_email_path, :remote => true, :html => { class: 'email_form' }, authenticity_token: true) do |f| %>
  <div class="table-panel">
    <div class="table-child child-label">From :</div>
    <div class="table-child cursor-not-allowed">no-reply@zevent.date</div>
  </div>
  <div class="table-panel">
    <div class="table-child child-label">To :</div>
    <div class="table-child">
      <%= f.email_field :to_email, class: "email-input-field no-outline", required: true %>
    </div>
  </div>
  <div class="table-panel">
    <div class="table-child child-label">Subject :</div>
    <div class="table-child">
      <%= f.text_field :subject, class: "email-input-field no-outline", required: true %>
    </div>
  </div>
  <div class="table-panel">
    <div class="table-child child-label ver-top">Body</div>
    <div class="table-child"><%= f.text_area :email_body, rows: "7", class: "label-content no-outline", required: true %></div>
  </div>
  <div class="submit-form text-right">
    <button type="submit" class="send-form-email js--send-email no-outline">
      Send
    </button>
  </div>
<% end %>

<script type="text/javascript">
  $('#newEmailModal .js--send-email').click(function(event) {
    $(this).html('Sending <i class="fa fa-spinner fa-spin" aria-hidden="true"></i>')
  });
</script>

app/views/admins/contact_message/_form_reply_email.html.erb
<%= form_for(@reply, url: admins_reply_messages_path, :remote => true, :html => { class: 'email_form' }, authenticity_token: true) do |f| %>
  <%= f.hidden_field :message_id, :value => target.id %>
  <div class="table-panel">
    <div class="table-child child-label">From :</div>
    <div class="table-child cursor-not-allowed">no-reply@zevent.date</div>
  </div>
  <div class="table-panel">
    <div class="table-child child-label">To :</div>
    <div class="table-child cursor-not-allowed"><%= target.email %></div>
  </div>
  <div class="table-panel">
    <div class="table-child child-label">Subject :</div>
    <div class="table-child cursor-not-allowed">[Reply] Thanks for contacting :: EVENT MAKER</div>
  </div>
  <div class="table-panel">
    <div class="table-child child-label ver-top">Body</div>
    <div class="table-child"><%= f.text_area :content, rows: "7", class: "label-content no-outline", required: true %></div>
  </div>
  <div class="submit-form text-right">
    <button type="submit" class="send-form-email js--send-email no-outline">
      Send
    </button>
  </div>
<% end %>

<script type="text/javascript">
  $('#contactMessageModal<%= target.id %> .js--send-email').click(function(event) {
    $(this).html('Sending <i class="fa fa-spinner fa-spin" aria-hidden="true"></i>')
  });
</script>

app/views/admins/contact_message/_reply_message_item.html.erb
<li>
  <div class="table-panel">
    <div class="table-child ver-mid label-title"><%= target.created_at.strftime("%Y %b %d %H:%M") %></div>
    <div class="table-child"><%= target.content %></div>
  </div>
</li>