config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'layouts', to: 'home#layouts', as: 'layouts'

  namespace :admins do
    resources :dashboard, only: [:index]
    resources :layouts, only: [:create]

    get 'layout', to: 'dashboard#layout', as: 'layout'
    get 'event_type', to: 'dashboard#event_type', as: 'event_type'
    get 'payment', to: 'dashboard#payment', as: 'payment'
    get 'messages', to: 'dashboard#messages', as: 'messages'

    post 'create_layout', to: 'dashboard#create_layout', as: 'create_layout'
    patch 'update_layout/:id', to: 'dashboard#update_layout', as: 'update_layout'
    put 'update_layout/:id', to: 'dashboard#update_layout'
    get 'layout/:id/edit', to: 'dashboard#edit_layout', as: 'edit_layout'
    delete 'destroy_layout/:id', to: 'dashboard#destroy_layout', as: 'destroy_layout'

    post 'create_event_type', to: 'dashboard#create_event_type', as: 'create_event_type'
    patch 'update_event_type/:id', to: 'dashboard#update_event_type', as: 'update_event_type'
    put 'update_event_type/:id', to: 'dashboard#update_event_type'
    delete 'destroy_event_type/:id', to: 'dashboard#destroy_event_type', as: 'destroy_event_type'

    post 'reply_messages', to: 'dashboard#reply_messages', as: 'reply_messages'
    post 'new_email', to: 'dashboard#new_email', as: 'new_email'
  end

  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :users do
    resources :dashboard, only: [:index]
    resources :events
    resources :cost_managements, only: [:create]
    resources :paypal
    resources :baokim

    devise_scope :user do
      get '/password/send_instructions' => 'passwords#send_instructions_successfull', as: 'send_instructions_successfull'
    end
  end

  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    unlocks: 'users/unlocks',
    omniauth_callbacks: "users/omniauth_callbacks",
    root: "home#index"
  }

  patch 'update_information/:id', to: 'users#update_information', as: 'update_information'
  put 'update_information/:id', to: 'users#update_information'

  post 'new_message', to: 'home#new_message', as: 'new_message'

  patch 'upload_avatar/:id', to: 'users#upload_avatar', as: 'upload_avatar'
  put 'upload_avatar/:id', to: 'users#upload_avatar'

  post 'get_district_ajax', to: 'users#get_district_ajax', as: 'get_district_ajax'
  post 'get_commune_ajax', to: 'users#get_commune_ajax', as: 'get_commune_ajax'
  post 'check_username_ajax', to: 'users#check_username_ajax', as: 'check_username_ajax'
  post 'check_event_slug_ajax', to: 'users/events#check_event_slug_ajax', as: 'check_event_slug_ajax'

  get ':username', to: 'users#show', as: :user

  post "/hook" => "users/paypal#hook"
  post "/baokim" => "users/baokim#create"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @message = Message.new
    @layouts = Layout.all.order('created_at DESC').limit(3)
  end

  def layouts
    @layouts = Layout.all

    @layout_type = []
    EventType.all.each do | type |
      @layout_type << type.label
    end
  end

  def new_message
    respond_to do |format|
      @message = Message.new(new_message_params)
      if @message.save
        @success = true
        ContactMailer.thanks_contacting_email( @message.name, @message.email, @message.message ).deliver
      else
        @success = false
      end
      format.js {}
    end
  end

  def new_message_params
    params.require(:message).permit(:name, :email, :message)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<section class="first-section">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="list-inline list-unstyled zevent-nav">
          <li class="nav-item">
            <%= link_to "Layouts", layouts_path, class: "no-outline" %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Dashboard", users_dashboard_index_path, class: "no-outline" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "no-outline" %>
            </li>
          <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to "Dashboard", admins_dashboard_index_path, class: "no-outline" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign out", destroy_admin_session_path, method: :delete, class: "no-outline" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: "no-outline" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign In", new_user_session_path, class: "no-outline" %>
            </li>
          <% end %>
        </ul>
        <div class="content-wrap">
          <div class="text-content">
            <h2>Welcome To Event Maker</h2>
            <div class="line-dec"></div>
            <span>Easy &amp; professional event management</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="second-section">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6">
        <div class="service-item">
          <div class="icon">
            <%= image_tag "vendor/first-icon.png" %>
          </div>
          <h4>Quick Editing</h4>
          <p>Aliquam ex velit, viverra eu tristique vel, rhoncus nec ligula. In vel massa sed dolor pharetra interdum vitae posuere.</p>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="service-item">
          <div class="icon">
            <%= image_tag "vendor/second-icon.png" %>
          </div>
          <h4>Responsive Layout</h4>
          <p>Sed pulvinar ipsum id leo volutpat, in convallis lectus molestie. Aliquam nisi sapien, faucibus eu consequat id, egestas vitae augue.</p>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="service-item">
          <div class="icon">
            <%= image_tag "vendor/third-icon.png" %>
          </div>
          <h4>Quick Support</h4>
          <p>Aliquam ex velit, viverra eu tristique vel, rhoncus nec ligula. In vel massa sed dolor pharetra interdum vitae posuere.</p>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="service-item">
          <div class="icon">
            <%= image_tag "vendor/fourth-icon.png" %>
          </div>
          <h4>Voice Chat</h4>
          <p>Sed pulvinar ipsum id leo volutpat, in convallis lectus molestie. Aliquam nisi sapien, faucibus eu consequat id, egestas vitae augue.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="third-section">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div class="left-image col-md-4">
          <%= image_tag "vendor/left-image.png" %>
        </div>
        <div class="right-text col-md-8">
          <h4><em>Integer suscipit</em><br>Nullam volutpat mi vel</h4>
          <p>Nulla tempor lectus at mauris bibendum porttitor. Aenean ultrices orci id nibh sodales, vel suscipit arcu vulputate. Pellentesque hendrerit diam quis leo dignissim, lacinia interdum nunc volutpat. Morbi lobortis mattis lectus, a dictum augue lobortis non. Fusce eu nulla sagittis, scelerisque eros fringilla, commodo dolor.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="fourth-section">
  <div class="container">
    <div class="row">
      <% @layouts.each do |layout| %>
        <div class="col-md-3 col-sm-6">
          <div class="portfolio-item item-<%= @layouts.index(layout) %>">
            <div class="image">
              <a href="<%= layout.featured_image.to_s %>" data-lightbox="image-<%= layout.id %>">
                <%= cl_image_tag(layout.featured_image.full_public_id, :transformation=>[{:width=>800, :height=>682, :gravity=>"auto", :crop=>"crop"}, {:width=>400, :height=>341, :crop=>"scale"}], class: "layout-image") %>
              </a>
            </div>
            <div class="text">
              <span><%= layout.event_types %></span>
              <h4><%= layout.name %></h4>
            </div>
          </div>
        </div>
      <% end %>
      <div class="col-md-3 col-sm-6">
        <div class="send-to-portfolio">
          <span>Do you want to see more?</span>
          <div class="primary-button">
            <%= link_to "Visit layouts", layouts_path, class: "no-outline" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="fivth-section">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1"> 
        <div class="left-text col-md-8">
          <h4><em>Aliquam efficitur</em><br>augue et libero vulputate feugiat</h4>
          <p>Mauris eget orci porta, aliquam neque sit amet, porttitor dui. Donec efficitur vehicula justo quis varius. Vivamus pharetra lorem eget turpis ornare tempus. Vivamus ac sodales lectus. Morbi rhoncus feugiat neque ultrices rhoncus. Maecenas ultrices, nisl pellentesque hendrerit dignissim, ante purus hendrerit urna, eu tristique est massa quis risus.</p>
        </div>
        <div class="right-image col-md-4">
          <%= image_tag "vendor/right-image.png" %>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="sixth-section">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="row">
          <%= form_for @message, url: new_message_path, :remote => true, authenticity_token: true, :html => {:id => "contact"} do |f| %>
            <div class="col-md-6">
              <fieldset>
                <%= f.text_field :name, class: "form-control no-outline", placeholder: "Your name...", required: true %>
              </fieldset>
            </div>
            <div class="col-md-6">
              <fieldset>
                <%= f.email_field :email, class: "form-control no-outline", placeholder: "Your email...", required: true %>
              </fieldset>
            </div>
            <div class="col-md-12">
              <fieldset>
                <%= f.text_area :message, rows: 6, class: "form-control no-outline", required: true, placeholder: "Your message..." %>
              </fieldset>
            </div>
            <div class="col-md-12">
              <fieldset>
                <button type="submit" id="form-submit" class="btn no-outline">
                  Send Message
                </button>
              </fieldset>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-md-5">
        <div class="right-info">
          <ul>
            <li><a href="#"><i class="fa fa-envelope"></i>contact@zevent.date</a></li>
            <li><a href="#"><i class="fa fa-phone"></i>(+84)869291156</a></li>
            <li><a href="#"><i class="fa fa-map-marker"></i>Ecogreen Nguyen Xien Ha Noi</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>

<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
          <li><a href="https://github.com/ngocquyhoang"><i class="fa fa-github"></i></a></li>
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
        </ul>
        <p>Copyright &copy; 2017 Event Maker | Design: <a href="https://ngocquyhoang.com" target="_blank">ngocquyhoang.com</a></p>
      </div>
    </div>
  </div>
</footer>

<div class="modal fade zevent-modal" id="successModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <button type="button" class="close-modal no-outline" data-dismiss="modal">
        <%= image_tag "vendor/close.png" %>
      </button>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-4 col-sm-12">
            <div class="modal-icon">
              <%= image_tag "vendor/success.svg" %>
            </div>
          </div>
          <div class="col-md-8 col-sm-12">
            <div class="modal-wrap-content">
              <h3>Thanks for being awesome!</h3>
              <p>Message was successful send!</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade zevent-modal" id="errorModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <button type="button" class="close-modal no-outline" data-dismiss="modal">
        <%= image_tag "vendor/close.png" %>
      </button>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-4 col-sm-12">
            <div class="modal-icon">
              <%= image_tag "vendor/error.svg" %>
            </div>
          </div>
          <div class="col-md-8 col-sm-12">
            <div class="modal-wrap-content">
              <h3>Something went wrong!</h3>
              <p>Please try again in a few minutes!</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).on('submit','form#contact',function(){
    $('#contact #form-submit').html('Sending email <i class="fa fa-spinner fa-spin" aria-hidden="true"></i>');
  });
</script>

app/views/home/layouts.html.erb
<section class="first-section">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="list-inline list-unstyled zevent-nav">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "no-outline" %>
          </li>
          <li class="nav-item">
            <%= link_to "Layouts", layouts_path, class: "no-outline" %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Dashboard", users_dashboard_index_path, class: "no-outline" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "no-outline" %>
            </li>
          <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to "Dashboard", admins_dashboard_index_path, class: "no-outline" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign out", destroy_admin_session_path, method: :delete, class: "no-outline" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: "no-outline" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign In", new_user_session_path, class: "no-outline" %>
            </li>
          <% end %>
        </ul>
        <div class="content-wrap">
          <div class="text-content">
            <h2>Layouts</h2>
            <div class="line-dec"></div>
            <span>ALL Layout You can choose</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="content-wrapper home-layouts-list">
  <div class="inner-container container">
    <div class="projects-holder-3">
      <div class="filter-categories">
        <ul class="project-filter">
          <li class="filter" data-filter="all"><span>All</span></li>
          <% @layout_type.each do |type| %>
            <li class="filter" data-filter="<%= get_slug(type) %>"><span><%= type %></span></li>
          <% end %>
        </ul>
      </div>
      <div class="projects-holder">
        <div class="row">
          <% @layouts.each do |layout| %>
            <div class="col-md-3 col-sm-6 project-item mix <%= get_slug( layout.event_types ).gsub('/', ' ') %>">
              <div class="image">
                <a href="<%= layout.featured_image.to_s %>" data-lightbox="image-<%= layout.id %>">
                  <%= cl_image_tag(layout.featured_image.full_public_id, :transformation=>[{:width=>800, :height=>600, :gravity=>"auto", :crop=>"crop"}, {:width=>400, :height=>300, :crop=>"scale"}], class: "layout-image") %>
                </a>
              </div>
              <div class="text">
                <span><%= layout.event_types %></span>
                <h4><%= layout.name %></h4>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div> 

<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
          <li><a href="https://github.com/ngocquyhoang"><i class="fa fa-github"></i></a></li>
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
        </ul>
        <p>Copyright &copy; 2017 Event Maker | Design: <a href="https://ngocquyhoang.com" target="_blank">ngocquyhoang.com</a></p>
      </div>
    </div>
  </div>
</footer>

app/views/home/new_message.js.erb
<% if @success %>
  $("#successModal").modal("show");
<% else %>
  $("#errorModal").modal("show");
<% end %>

$('#contact #form-submit').html('Send Message');
$("#message_name").val("");
$("#message_email").val("");
$("#message_message").val("");