config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'layouts', to: 'home#layouts', as: 'layouts'

  namespace :admins do
    resources :dashboard, only: [:index]
    resources :layouts, only: [:create]

    get 'layout', to: 'dashboard#layout', as: 'layout'
    get 'event_type', to: 'dashboard#event_type', as: 'event_type'
    get 'payment', to: 'dashboard#payment', as: 'payment'
    get 'messages', to: 'dashboard#messages', as: 'messages'

    post 'create_layout', to: 'dashboard#create_layout', as: 'create_layout'
    patch 'update_layout/:id', to: 'dashboard#update_layout', as: 'update_layout'
    put 'update_layout/:id', to: 'dashboard#update_layout'
    get 'layout/:id/edit', to: 'dashboard#edit_layout', as: 'edit_layout'
    delete 'destroy_layout/:id', to: 'dashboard#destroy_layout', as: 'destroy_layout'

    post 'create_event_type', to: 'dashboard#create_event_type', as: 'create_event_type'
    patch 'update_event_type/:id', to: 'dashboard#update_event_type', as: 'update_event_type'
    put 'update_event_type/:id', to: 'dashboard#update_event_type'
    delete 'destroy_event_type/:id', to: 'dashboard#destroy_event_type', as: 'destroy_event_type'

    post 'reply_messages', to: 'dashboard#reply_messages', as: 'reply_messages'
    post 'new_email', to: 'dashboard#new_email', as: 'new_email'
  end

  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :users do
    resources :dashboard, only: [:index]
    resources :events
    resources :cost_managements, only: [:create]
    resources :paypal
    resources :baokim

    devise_scope :user do
      get '/password/send_instructions' => 'passwords#send_instructions_successfull', as: 'send_instructions_successfull'
    end
  end

  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    unlocks: 'users/unlocks',
    omniauth_callbacks: "users/omniauth_callbacks",
    root: "home#index"
  }

  patch 'update_information/:id', to: 'users#update_information', as: 'update_information'
  put 'update_information/:id', to: 'users#update_information'

  post 'new_message', to: 'home#new_message', as: 'new_message'

  patch 'upload_avatar/:id', to: 'users#upload_avatar', as: 'upload_avatar'
  put 'upload_avatar/:id', to: 'users#upload_avatar'

  post 'get_district_ajax', to: 'users#get_district_ajax', as: 'get_district_ajax'
  post 'get_commune_ajax', to: 'users#get_commune_ajax', as: 'get_commune_ajax'
  post 'check_username_ajax', to: 'users#check_username_ajax', as: 'check_username_ajax'
  post 'check_event_slug_ajax', to: 'users/events#check_event_slug_ajax', as: 'check_event_slug_ajax'

  get ':username', to: 'users#show', as: :user

  post "/hook" => "users/paypal#hook"
  post "/baokim" => "users/baokim#create"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :event_type
  has_one :layout
  has_many :cost_managements

  validate :start_time_validation
  validate :end_time_validation

  validates :slug, uniqueness: true, presence: true, length: { in: 3..12 }
  validates :name, presence: true
  validates :user_id, presence: true
  validates :layout_id, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :main_description, presence: true
  validates :address, presence: true
  validates :event_type_id, presence: true
  validates :address_commune, presence: true
  validates :address_district, presence: true
  validates :address_province, presence: true
  validates :expense, presence: true
  validates :title_layout, presence: true
  validates :seo_keyword, presence: true

  def start_time_validation
    if self.start_time.present? && self.start_time < Date.today
      errors.add(:start_time, "can't be in the past")
    end
  end

  def end_time_validation
    if self.end_time.present?
      if self.end_time < Date.today
        errors.add(:start_time, "can't be in the past")
      elsif self.start_time.present? && self.end_time < self.start_time
        errors.add(:start_time, "can't be less than start date")
      end
    end
  end
end

app/controllers/users/access_controller.rb
class Users::AccessController < ApplicationController
  before_action :authenticate_user!
  before_action :set_global_layout
  
  layout :user_layout

  protected
  def user_layout
    "users/layouts/application"
  end

  def set_global_layout
    @is_global_layout = true
  end
end

app/controllers/users/baokim_controller.rb
class Users::BaokimController < ApplicationController

 def new
    amount = 0
    name = "test"
    item_num = 0
    @baokim = Baokim.new
    case params[:status]
      when  "pro"
        amount = 100
        name = "Upgrade account to Professional"
        item_num = 1
      when  "pro_plus"
        amount = 1000
        name = "Upgrade account to Professional Plus"
        item_num = 2
    end
    redirect_to @baokim.baokim_url amount, name, item_num, current_user.id, users_dashboard_index_path
 end

 def create
   params.permit!
   status = params[:transaction_status]
   if status == 4
     @paypal = Paypal.new
     @paypal.update_attributes notification_params: params, status: status,
      transaction_id: params[:transaction_id], purchased_at: Time.now
     item = params[:order_id]
     user = User.find_by_id(params[:user_id])
     case item
       when "1"
         user.update_attributes acc_state: 1 if user
         flash[:success] = "Upgraded to Professional!!"
       when "2"
         user.update_attributes acc_state: 2 if user
         flash[:success] = "Upgraded to Professional Plus!!"
     end
   end
   redirect_to users_dashboard_index_path
 end
end

app/controllers/users/cost_managements_controller.rb
class Users::CostManagementsController < Users::AccessController
  before_action :load_cost, only: [:create]

  def create
    log = CostManagement.new
    log.update_attributes cost_params

    respond_to do |format|
      format.js { render file: "/users/events/create_cost_management.js.erb" }
    end
  end

  private
  def cost_params
    params.require(:cost_management).permit :cost_type, :amount, :note, :user_id, :event_id
  end

  def load_cost
    @cost_log = CostManagement.where(event_id: params[:cost_management][:event_id]).order(id: :desc)
  end
end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < Users::AccessController
  include UsersHelper
  before_action :load_event, only: [:index]

  def index; end
end

app/controllers/users/events_controller.rb
class Users::EventsController < Users::AccessController
  include UsersHelper
  before_action :find_event, only: [:show, :update, :edit, :destroy]
  before_action :load_event, only: [:create]
  before_action :load_cost, only: [:show]
  before_action :check_state, only: [:new, :create]

  def show
  end

  def new
    @event = Event.new
    @layouts = Layout.all
    @event_types = EventType.all

    @address_province_list = ActiveSupport::JSON.decode(File.read('databases/address_province.json'))
    @distric_list_of_province = get_district_list(@event.address_province)
    @commune_list_of_province = get_commune_list(@event.address_province, @event.address_district)
  end

  def create
    @event = Event.new event_params
    if @event.save
      flash[:success] = "Event was created!"
      redirect_to users_dashboard_index_path
    else
      flash[:error] = "Something went wrong please try again later!"
      redirect_to new_users_event_path
    end
  end

  def edit
    @layouts = Layout.all
    @event_types = EventType.all

    @address_province_list = ActiveSupport::JSON.decode(File.read('databases/address_province.json'))
    @distric_list_of_province = get_district_list(@event.address_province)
    @commune_list_of_province = get_commune_list(@event.address_province, @event.address_district)
  end

  def update
    if @event.update event_params
      flash[:success] = "Event was successful updated!"
    else
      flash[:error] = "Something went wrong please try again later!"
      redirect_to edit_users_event_path(@event)
    end
  end

  def destroy
    if @event.destroy
      flash[:success] = "Event was successful destroy!"
      redirect_to user_path(current_user.username)
    else
      flash[:error] = "Something went wrong please try again later!"
    end
  end

  def check_event_slug_ajax
    is_valid = Event.new(name: 'BD', slug: params['event_slug'], user_id: 1, layout_id: 1, start_time: '01-12-2017 08:00', end_time: '01-12-2017 17:00', main_description: 'BD', address: 'BD', event_type_id: 1, address_commune: 'BD', address_district: 'BD', address_province: 'BD', expense: 2000, title_layout: 'BD', seo_keyword: 'BD').valid?
    render json: { 'is_valid': is_valid }
  end

  private
  def event_params
    params.require(:event).permit(:name, :title_layout, :slug, :user_id, :start_time, :end_time, :main_description, :sub_description, :layout_id, :event_type_id, :address, :address_commune, :address_district, :address_province, :est_amount_people, :expense, :seo_keyword, :google_form_url)
  end

  def find_event
    @event = Event.find_by id: params[:id]
  end

  def load_cost
    @cost_log = CostManagement.where(event_id: params[:id]).order(id: :desc)
  end

  def check_state
    if current_user.acc_state == "free"
      unless current_user.events.count < 1
        redirect_to user_path(current_user.username)
        flash[:error] = "Please upgrade your account to create more event"
      end
    elsif current_user.acc_state == "pro"
      unless current_user.events.count < 5
        redirect_to user_path(current_user.username)
        flash[:error] = "Please upgrade your account to create more event"
      end
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  include AccessibleAdmin

  layout :user_layout

  def facebook
    generic_callback("facebook")
  end

  def google_oauth2
    generic_callback("google")
  end

  def generic_callback provider
    @identity = User.from_omniauth(request.env["omniauth.auth"])

    @user = @identity || current_user
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, kind: provider.capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  protected

  def user_layout
    "users/layouts/application"
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include AccessibleAdmin
  
  layout :user_layout

  def send_instructions_successfull
  end

  protected
  def user_layout
    "users/layouts/application"
  end

  def after_sending_reset_password_instructions_path_for(resource_name)
    users_send_instructions_successfull_path
  end
end

app/controllers/users/paypal_controller.rb
class Users::PaypalController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:hook]
  protect_from_forgery except: [:hook]

  def new
    amount = 0
    name = "test"
    item_num = 0
    @paypal = Paypal.new
    case params[:status]
      when  "pro"
        amount = 100
        name = "Upgrade account to Professional"
        item_num = 1
      when  "pro_plus"
        amount = 1000
        name = "Upgrade account to Professional Plus"
        item_num = 2
    end
    redirect_to @paypal.paypal_url amount, name, item_num, current_user.id, users_dashboard_index_path
  end

  def hook
    params.permit!
    status = params[:payment_status]
    if status == "Completed"
      @paypal = Paypal.new
      @paypal.update_attributes notification_params: params, status: status,
        transaction_id: params[:txn_id], purchased_at: Time.now
      item = params[:item_number]
      user = User.find_by_id(params[:user_id])
      case item
        when "1"
          user.update_attributes acc_state: 1 if user
          flash[:success] = "Upgraded to Professional!!"
        when "2"
          user.update_attributes acc_state: 2 if user
          flash[:success] = "Upgraded to Professional Plus!!"
      end
    end
    redirect_to users_dashboard_index_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include AccessibleAdmin
  skip_before_action :check_admin, only: [:edit, :update, :destroy]
  before_action :set_global_layout, only: :edit

  layout :user_layout

  def destroy  
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)  
    set_flash_message :notice, :destroyed if is_flashing_format?  
    yield resource if block_given?  
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }  
  end 

  protected
  def user_layout
    "users/layouts/application"
  end

  def set_global_layout
    @is_global_layout = true
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include AccessibleAdmin
  skip_before_action :check_admin, only: :destroy

  layout :user_layout

  protected
    def user_layout
      "users/layouts/application"
    end

    def after_sign_in_path_for(resource)
      users_dashboard_index_path
    end

    def after_sign_up_path_for(resource)
      users_dashboard_index_path
    end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  include AccessibleAdmin
  
  layout :user_layout

  protected
  def user_layout
    "users/layouts/application"
  end
end

app/controllers/users_controller.rb
class UsersController < Users::AccessController
  include UsersHelper
  before_action :show_user, only: :show
  before_action :set_user, except: [
    :show,
    :get_district_ajax,
    :get_commune_ajax,
    :get_highschool_district_ajax,
    :get_highschool_list_ajax,
    :check_username_ajax
  ]

  def show
    redirect_to users_dashboard_index_path unless @user

    if @user == current_user
      @jobs = get_job_list
      @like_dislike_list = get_like_dislike_list

      @address_province_list = ActiveSupport::JSON.decode(File.read('databases/address_province.json'))
      @distric_list_of_province = get_district_list(@user.address_province)
      @commune_list_of_province = get_commune_list(@user.address_province, @user.address_district)
    end
  end

  def upload_avatar
    if @user == current_user
      respond_to do |format|
        @user.reload if @user.update(user_avatar_params)
        format.js {}
      end
    end
  end

  def update_information
    infor_params = user_information_params.to_h
    infor_params[:job].shift
    infor_params[:job] = infor_params[:job].join("|")
    infor_params[:hobby].shift
    infor_params[:hobby] = infor_params[:hobby].join("|")
    infor_params[:dislike].shift
    infor_params[:dislike] = infor_params[:dislike].join("|")

    if @user == current_user
      respond_to do |format|
        @user.reload if @user.update(infor_params)
        format.js {}
      end
    end
  end

  def get_district_ajax
    render json: { 'distric_list': get_district_list(params['province']) }
  end

  def get_commune_ajax
    render json: { 'commune_list': get_commune_list(params['province'], params['district']) }
  end

  def check_username_ajax
    if params['username'] != current_user.username
      is_valid = User.new(email: 'user@example.com', password: '123456789', password_confirmation: '123456789', username: params['username']).valid?
      render json: { 'is_valid': is_valid }
    else
      render json: { 'is_valid': true }
    end
  end

  private

  def show_user
    @user = User.find_by_username( params[:username] )
    @user = User.find_by_id( params[:username] ) unless @user
  end

  def set_user
    @user = User.find params[:id]
  end

  def user_information_params
    params.require(:user).permit(:username, :name, :gender, :dob, { :job => [] }, { :hobby => [] }, { :dislike => [] }, :address_commune, :address_district, :address_province, :highschool_province, :highschool_district, :high_school, :univesity)
  end

  def user_avatar_params
    params.require(:user).permit(:avatar)
  end
end

app/helpers/users/dashboard_helper.rb
module Users::DashboardHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def get_district_list province
    distric_list = ActiveSupport::JSON.decode(File.read('databases/address_district.json'))
    distric_list_of_province = []
    distric_list.each do |district|
      distric_list_of_province << district if district['Ten_Tinh_Thanh_Pho'] == province
    end

    return distric_list_of_province
  end

  def get_commune_list(province, district)
    commune_list = ActiveSupport::JSON.decode(File.read('databases/address_commune.json'))
    commune_list_of_province = []
    commune_list.each do |commune|
      if commune['Ten_Tinh_Thanh_Pho'] == province && commune['Ten_Quan_Huyen'] == district
        commune_list_of_province << commune
      end
    end

    return commune_list_of_province
  end

  def get_job_list
    jobs = []
    File.readlines('databases/job_list.txt').map do |line|
      jobs << line.split("\r\n")[0]
    end

    return jobs
  end

  def get_like_dislike_list
    like_dislike_list = []
    File.readlines('databases/like_disklike_list.txt').map do |line|
      like_dislike_list << line.split("\r\n")[0]
    end
    like_dislike_list = like_dislike_list.uniq

    return like_dislike_list
  end

  def load_event
    @events = Event.where(user_id: current_user.id).order(id: :desc)
  end
end

app/views/users/events/new.html.erb
<div class="user-wrapper">
  <div class="user-event-screen">
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-md-offset-1 col-sm-12">
          <h2 class="screen-title">Create New Event</h2>
          <%= form_for(@event, method: :post, url: users_events_path, html: {id: 'event-form'}) do |f| %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <div class="form-group">
              <div class="table-panel">
                <div class="table-child ver-mid">
                  Event Name <span class="required-mark">（＊）</span>
                </div>
                <div class="table-child ver-mid">
                  <%= f.text_field :name, class:"form-control", required: true %>
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class="table-panel">
                <div class="table-child ver-mid">
                  Website Title <span class="required-mark">（＊）</span>
                </div>
                <div class="table-child ver-mid">
                  <%= f.text_field :title_layout, class:"form-control", required: true %>
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class="table-panel">
                <div class="table-child ver-mid">
                  Website URL <span class="required-mark">（＊）</span>
                </div>
                <div class="table-child ver-mid">
                  <div class="input-group">
                    <div class="input-group-addon">https://</div>
                    <%= f.text_field :slug, class:"form-control slug-input", required: true %>
                    <div class="input-group-addon">.zevent.date</div>
                  </div>
                  <div id="event_slug_error" class="invalid-feedback text-black">( Between 3 and 12 characters for a url is acceptable )</div>
                </div>
              </div>
            </div>
            <script type="text/javascript">
              $('#event_slug').keyup( function () {
                if (this.value.length >= 3 && this.value.length <= 12) {
                  $('#event_slug').removeClass('is-invalid');
                  $('#event_slug_error').addClass('text-black');
                  $.ajax({
                    url: '<%= check_event_slug_ajax_path %>',
                    data: { 'event_slug' : this.value },
                    type: 'post',
                    success: function(result){
                      if (result.is_valid) {
                        $('#event_slug').removeClass('is-invalid');
                        $('#event_slug').addClass('is-valid');
                        $('#event_slug_error').text('( Between 3 and 12 characters for a url is acceptable )');
                      }else {
                        $('#event_slug').removeClass('is-valid');
                        $('#event_slug').addClass('is-invalid');
                        $('#event_slug_error').removeClass('text-black');
                        $('#event_slug_error').text('( This url is already in use )');
                      }
                    }}
                  );
                }else {
                  $('#event_slug').removeClass('is-valid');
                  $('#event_slug').addClass('is-invalid');
                  $('#event_slug_error').removeClass('text-black');
                  $('#event_slug_error').text('( Between 3 and 12 characters for a url is acceptable )');
                }
              })
            </script>
            <div class="form-group">
              <div class="table-panel">
                <div class="table-child ver-mid">
                  Layout <span class="required-mark">（＊）</span>
                </div>
                <div class="table-child ver-mid">
                  <%= f.select :layout_id, @layouts.collect { |layout| [ layout.title, layout.id ] }, { include_blank: 'Select Event Layout' }, class:"ui dropdown js--select-layout semantic-ui-form" %>
                  <script type="text/javascript">
                    $('.js--select-layout').dropdown();
                  </script>
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class="table-panel">
                <div class="table-child ver-mid">
                  Event Type 
                </div>
                <div class="table-child ver-mid">
                  <%= f.select :event_type_id, @event_types.collect { |type| [ type.label, type.id ] }, { include_blank: 'Select Event Type' }, class:"ui dropdown js--select-event-type semantic-ui-form" %>

                  <script type="text/javascript">
                    $('.js--select-event-type').dropdown();
                  </script>
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class="row">
                <div class="col-md-6">
                  <div class="table-panel">
                    <div class="table-child ver-mid">
                      Start time <span class="required-mark">（＊）</span>
                    </div>
                    <div class="table-child ver-mid">
                      <%= f.text_field :start_time, class:"form-control js--event-start-time", required: true %>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="table-panel">
                    <div class="table-child ver-mid">
                      End time <span class="required-mark">（＊）</span>
                    </div>
                    <div class="table-child ver-mid">
                      <%= f.text_field :end_time, class:"form-control js--event-end-time", required: true %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class="row">
                <div class="col-md-6">
                  <div class="table-panel">
                    <div class="table-child ver-mid">
                      Event expense <span class="required-mark">（＊）</span>
                    </div>
                    <div class="table-child ver-mid">
                      <div class="input-group">
                        <%= f.number_field :expense, class:"form-control", min: 0, required: true %>
                        <div class="input-group-addon">$ USD</div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="table-panel">
                    <div class="table-child ver-mid">
                      Amount People 
                    </div>
                    <div class="table-child ver-mid">
                      <div class="input-group">
                        <%= f.number_field :est_amount_people, class:"form-control",  min: 0 %>
                        <div class="input-group-addon"><i class="fa fa-child" aria-hidden="true"></i></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class="table-panel">
                <div class="table-child ver-top">
                  Event Address <span class="required-mark">（＊）</span>
                </div>
                <div class="table-child ver-mid">
                  <div class="form-group">
                    <%= f.select :address_province, @address_province_list.collect { |ap| [ ap['Ten_Tinh_Thanh_Pho'], ap['Ten_Tinh_Thanh_Pho'] ] }, { include_blank: 'Select Province of Event address' }, class: "ui search dropdown js--select-address-province semantic-ui-form width-100" %>
                  </div>
                  <div class="form-group">
                    <%= f.select :address_district, @distric_list_of_province.collect { |ap| [ ap['Ten_Quan_Huyen'], ap['Ten_Quan_Huyen'] ] }, { include_blank: 'Select District of Event address' }, class: "ui search dropdown js--select-address-district semantic-ui-form width-100" %>
                  </div>
                  <div class="form-group">
                    <%= f.select :address_commune, @commune_list_of_province.collect { |ap| [ ap['Ten_Phuong_Xa'], ap['Ten_Phuong_Xa'] ] }, { include_blank: 'Select Commune of Event address' }, class: "ui search dropdown js--select-address-commune semantic-ui-form width-100" %>
                  </div>
                  <div class="form-group">
                    <%= f.text_field :address, class:"form-control", required: true, placeholder: "Ex: P1912 CT3 Ecogreen 268 Nguyen Xien ..." %>
                  </div>

                  <script type="text/javascript">
                    $('.js--select-address-province').dropdown();
                    $('.js--select-address-district').dropdown();
                    $('.js--select-address-commune').dropdown();
                  </script>

                  <script type="text/javascript">
                    $('#event_address_province').on('change', function() {
                      $.ajax({
                        url: '<%= get_district_ajax_path %>',
                        data: { 'province' : this.value },
                        type: 'post',
                        success: function(result){
                          $('#event_address_district').children('option:not(:first)').remove();
                          $('#event_address_commune').children('option:not(:first)').remove();
                          $('.js--select-address-district > .text').text('Select your District');
                          $('.js--select-address-commune > .text').text('Select your Commune');
                          $.each(result.distric_list, function(index, value) {
                            $('#event_address_district')
                              .append($("<option></option>")
                              .attr("value",value.Ten_Quan_Huyen)
                              .text(value.Ten_Quan_Huyen));
                          });
                        }}
                      );
                    })

                    $('#event_address_district').on('change', function() {
                      $.ajax({
                        url: '<%= get_commune_ajax_path %>',
                        data: { 'province' : $('#event_address_province').val(), 'district' : this.value },
                        type: 'post',
                        success: function(result){
                          $('#event_address_commune').children('option:not(:first)').remove();
                          $('.js--select-address-commune > .text').text('Select your Commune');
                          $.each(result.commune_list, function(index, value) {
                            $('#event_address_commune')
                              .append($("<option></option>")
                              .attr("value",value.Ten_Phuong_Xa)
                              .text(value.Ten_Phuong_Xa));
                          });
                        }}
                      );
                    })
                  </script>
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class="table-panel">
                <div class="table-child ver-mid">
                  Google Form URL
                </div>
                <div class="table-child ver-mid">
                  <%= f.text_field :google_form_url, class:"form-control" %>
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class="table-panel">
                <div class="table-child ver-mid">
                  SEO Keyword <span class="required-mark">（＊）</span>
                </div>
                <div class="table-child ver-mid">
                  <%= f.text_area :seo_keyword, rows: 3, class:"form-control", required: true %>
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class="table-panel">
                <div class="table-child ver-mid">
                  Main Description <span class="required-mark">（＊）</span>
                </div>
                <div class="table-child ver-mid">
                  <%= f.text_area :main_description, rows: 6, class:"form-control", required: true %>
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class="table-panel">
                <div class="table-child ver-mid">
                  Sub Description
                </div>
                <div class="table-child ver-mid">
                  <%= f.text_area :sub_description, rows: 6, class:"form-control" %>
                </div>
              </div>
            </div>

            <div class="form-group submit-group text-right">
              <button type="submit" class="btn event-form-submit-button">
                Create Event
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('.js--event-start-time').datetimepicker({
    format: 'DD-MM-YYYY HH:mm',
    minDate: new Date(),
    sideBySide: true,
  });

  $('.js--event-end-time').datetimepicker({
    format: 'DD-MM-YYYY HH:mm',
    minDate: new Date(),
    sideBySide: true,
    useCurrent: false
  });

  $(".js--event-start-time").on("dp.change", function(e) {
    $('.js--event-end-time').data("DateTimePicker").minDate(e.date);
  });
  $(".js--event-end-time").on("dp.change", function(e) {
    $('.js--event-start-time').data("DateTimePicker").maxDate(e.date);
  });
</script>