config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'layouts', to: 'home#layouts', as: 'layouts'

  namespace :admins do
    resources :dashboard, only: [:index]
    resources :layouts, only: [:create]

    get 'layout', to: 'dashboard#layout', as: 'layout'
    get 'event_type', to: 'dashboard#event_type', as: 'event_type'
    get 'payment', to: 'dashboard#payment', as: 'payment'
    get 'messages', to: 'dashboard#messages', as: 'messages'

    post 'create_layout', to: 'dashboard#create_layout', as: 'create_layout'
    patch 'update_layout/:id', to: 'dashboard#update_layout', as: 'update_layout'
    put 'update_layout/:id', to: 'dashboard#update_layout'
    get 'layout/:id/edit', to: 'dashboard#edit_layout', as: 'edit_layout'
    delete 'destroy_layout/:id', to: 'dashboard#destroy_layout', as: 'destroy_layout'

    post 'create_event_type', to: 'dashboard#create_event_type', as: 'create_event_type'
    patch 'update_event_type/:id', to: 'dashboard#update_event_type', as: 'update_event_type'
    put 'update_event_type/:id', to: 'dashboard#update_event_type'
    delete 'destroy_event_type/:id', to: 'dashboard#destroy_event_type', as: 'destroy_event_type'

    post 'reply_messages', to: 'dashboard#reply_messages', as: 'reply_messages'
    post 'new_email', to: 'dashboard#new_email', as: 'new_email'
  end

  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :users do
    resources :dashboard, only: [:index]
    resources :events
    resources :cost_managements, only: [:create]
    resources :paypal
    resources :baokim

    devise_scope :user do
      get '/password/send_instructions' => 'passwords#send_instructions_successfull', as: 'send_instructions_successfull'
    end
  end

  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    unlocks: 'users/unlocks',
    omniauth_callbacks: "users/omniauth_callbacks",
    root: "home#index"
  }

  patch 'update_information/:id', to: 'users#update_information', as: 'update_information'
  put 'update_information/:id', to: 'users#update_information'

  post 'new_message', to: 'home#new_message', as: 'new_message'

  patch 'upload_avatar/:id', to: 'users#upload_avatar', as: 'upload_avatar'
  put 'upload_avatar/:id', to: 'users#upload_avatar'

  post 'get_district_ajax', to: 'users#get_district_ajax', as: 'get_district_ajax'
  post 'get_commune_ajax', to: 'users#get_commune_ajax', as: 'get_commune_ajax'
  post 'check_username_ajax', to: 'users#check_username_ajax', as: 'check_username_ajax'
  post 'check_event_slug_ajax', to: 'users/events#check_event_slug_ajax', as: 'check_event_slug_ajax'

  get ':username', to: 'users#show', as: :user

  post "/hook" => "users/paypal#hook"
  post "/baokim" => "users/baokim#create"
end

app/controllers/admins/dashboard_controller.rb
class Admins::DashboardController < Admins::AccessController
  before_action :set_event_type, only: [:update_event_type, :destroy_event_type]
  before_action :set_layout, only: [:edit_layout, :update_layout, :destroy_layout]

  # DASHBOARD BLOCK #################################

  def index
    @event_count = Event.count
    @message_count = Message.count
    @layout_count = Layout.count
    @user_count = User.count
  end

  # LAYOUT BLOCK ####################################

  def layout
    @new_layout = Layout.new

    @layouts = Layout.all

    @event_types = []

    EventType.all.each do |type|
      @event_types << type.label
    end
  end

  def create_layout
    new_layout_params = layout_params.to_h
    new_layout_params[:event_types].shift
    new_layout_params[:event_types] = new_layout_params[:event_types].join(" / ")

    @layout = Layout.new( new_layout_params )

    respond_to do |format|
      @layout.save ? ( @save_success = true ) : ( @save_success = false )
      @layout.reload

      format.js {}
    end
  end

  def edit_layout
    @event_types = []

    EventType.all.each do |type|
      @event_types << type.label
    end
  end

  def update_layout
    new_layout_params = layout_params.to_h
    new_layout_params[:event_types].shift
    new_layout_params[:event_types] = new_layout_params[:event_types].join(" / ")

    respond_to do |format|
      @layout.update( new_layout_params ) ? ( @update_success = true ) : ( @update_success = false )
      @layout.reload

      format.js {}
    end
  end

  def destroy_layout
    @layout.destroy
    flash[:success] = "Layout was successfully deleted"
    redirect_to admins_layout_path
  end

  # EVENT TYPE BLOCK ################################

  def event_type
    @event_type = EventType.new

    @event_types = EventType.all.order('created_at DESC')
  end

  def create_event_type
    @event_type = EventType.new( event_type_params )

    respond_to do |format|
      @event_type.save ? ( @save_success = true ) : ( @save_success = false )

      format.js {}
    end
  end

  def update_event_type
    respond_to do |format|
      @event_type.update( event_type_params ) ? ( @update_success = true ) : ( @update_success = false )
      @event_type.reload

      format.js {}
    end
  end

  def destroy_event_type
    respond_to do |format|
      @event_type.destroy
      format.js {}
    end
  end

  # PAYMENT BLOCK ###################################

  def payment
  end

  # MESSAGES BLOCK ##################################

  def messages
    @messages = Message.all.order('created_at DESC')
    @new_email = AdminEmail.new

    @reply = ReplyMessage.new()
  end

  def reply_messages
    @reply_messages = ReplyMessage.new(reply_message_params)

    respond_to do |format|
      if @reply_messages.save
        ContactMailer.reply_contact_email( @reply_messages.message, @reply_messages.content ).deliver
        @save_success = true
      else
        @save_success = false
      end
      format.js {}
    end
  end

  def new_email
    @new_message = AdminEmail.new(new_message_params)

    respond_to do |format|
      if @new_message.save
        ContactMailer.send_new_email( @new_message.subject, @new_message.to_email, @new_message.email_body ).deliver
        @save_success = true
      else
        @save_success = false
      end
      format.js {}
    end
  end

  private

  def event_type_params
    params.require(:event_type).permit(:label)
  end

  def reply_message_params
    params.require(:reply_message).permit(:content, :message_id)
  end

  def new_message_params
    params.require(:admin_email).permit(:to_email, :subject, :email_body)
  end

  def layout_params
    params.require(:layout).permit(:name, { :event_types => [] }, :featured_image, :html, :css, :javascript)
  end

  def set_event_type
    @event_type = EventType.find( params[:id] )
  end

  def set_layout
    @layout = Layout.find(params[:id])
  end
end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < Users::AccessController
  include UsersHelper
  before_action :load_event, only: [:index]

  def index; end
end

app/helpers/admins/dashboard_helper.rb
module Admins::DashboardHelper
end

app/helpers/users/dashboard_helper.rb
module Users::DashboardHelper
end

app/views/admins/dashboard/_dashboard_slide.html.erb
<ul class="list-unstyled">
  <li class="slide-item">
    <% if current_page?(admins_dashboard_index_path) %>
      <%= link_to admins_dashboard_index_path, class: "active no-outline" do %>
        <i class="fa fa-bar-chart" aria-hidden="true"></i>
        <span>Dashboard</span>
      <% end %>
    <% else %>
      <%= link_to admins_dashboard_index_path, class: "no-outline" do %>
        <i class="fa fa-bar-chart" aria-hidden="true"></i>
        <span>Dashboard</span>
      <% end %>
    <% end %>
  </li>
  <li class="slide-item">
    <% if current_page?(admins_messages_path) %>
      <%= link_to admins_messages_path, class: "active no-outline" do %>
        <i class="fa fa-envelope-open-o" aria-hidden="true"></i>
        <span>Messages</span>
      <% end %>
    <% else %>
      <%= link_to admins_messages_path, class: "no-outline" do %>
        <i class="fa fa-envelope-open-o" aria-hidden="true"></i>
        <span>Messages</span>
      <% end %>
    <% end %>
  </li>
  <li class="slide-item">
    <% if current_page?(admins_layout_path) %>
      <%= link_to admins_layout_path, class: "active no-outline" do %>
        <i class="fa fa-sticky-note-o" aria-hidden="true"></i>
        <span>Layout</span>
      <% end %>
    <% else %>
      <%= link_to admins_layout_path, class: "no-outline" do %>
        <i class="fa fa-sticky-note-o" aria-hidden="true"></i>
        <span>Layout</span>
      <% end %>
    <% end %>
  </li>
  <li class="slide-item">
    <% if current_page?(admins_event_type_path) %>
      <%= link_to admins_event_type_path, class: "active no-outline" do %>
        <i class="fa fa-list-ul" aria-hidden="true"></i>
        <span>Event Type</span>
      <% end %>
    <% else %>
      <%= link_to admins_event_type_path, class: "no-outline" do %>
        <i class="fa fa-list-ul" aria-hidden="true"></i>
        <span>Event Type</span>
      <% end %>
    <% end %>
  </li>
  <li class="slide-item">
    <% if current_page?(admins_payment_path) %>
      <%= link_to admins_payment_path, class: "active no-outline" do %>
        <i class="fa fa-credit-card-alt" aria-hidden="true"></i>
        <span>Payment</span>
      <% end %>
    <% else %>
      <%= link_to admins_payment_path, class: "no-outline" do %>
        <i class="fa fa-credit-card-alt" aria-hidden="true"></i>
        <span>Payment</span>
      <% end %>
    <% end %>
  </li>
  <li class="slide-item">
    <% if current_page?(edit_admin_registration_path) %>
      <%= link_to edit_admin_registration_path, class: "active no-outline" do %>
        <i class="fa fa-cog fa-spin" aria-hidden="true"></i>
        <span>Setting</span>
      <% end %>
    <% else %>
      <%= link_to edit_admin_registration_path, class: "no-outline" do %>
        <i class="fa fa-cog fa-spin" aria-hidden="true"></i>
        <span>Setting</span>
      <% end %>
    <% end %>
  </li>
  <li class="slide-item">
    <%= link_to destroy_admin_session_path, method: :delete, class: "no-outline" do %>
      <i class="fa fa-sign-out" aria-hidden="true"></i>
      <span>Sign out</span>
    <% end %>
  </li>
</ul>

app/views/admins/dashboard/_event_type_item.html.erb
<li class="type-item cursor-pointer" data-toggle="modal" data-target="#editEventType<%= type.id %>" data-type-id="<%= type.id %>">
  <%= type.label %>
</li>
<div class="modal fade zevent-modal" id="editEventType<%= type.id %>" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <button type="button" class="close-modal no-outline" data-dismiss="modal">
        <%= image_tag "vendor/close.png" %>
      </button>
      <div class="modal-body text-center">
        <h3 class="modal-title">Edit Event Type</h3>
        <div class="event-type-form-modal">
          <div class="event-type-form">
            <%= form_for(type, url: admins_update_event_type_path( type ), :remote => true, authenticity_token: true) do |f| %>
              <%= f.text_field :label, class: "label-field no-outline", required: true %>
              <%= f.submit "Update", class: "submit-event-type no-outline" %>
              <%= link_to admins_destroy_event_type_path( type ), method: :delete, remote: true, class: 'delete-event-type no-outline' do %>
                Delete
                <i class="fa fa-trash-o" aria-hidden="true"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/dashboard/create_event_type.js.erb
<% if @save_success %>
  $('#event_type_list').prepend("<%= j render 'admins/dashboard/event_type_item', type: @event_type %>");
  $('#event_type_label').val('');
<% else %>
  $('#event_type_label').val('');
<% end %>

app/views/admins/dashboard/create_layout.js.erb
<% if @save_success %>
  $('#admins_layout_list').append('<%= j render "admins/track_layout/layout_item", target_layout: @layout  %>');
  $('#newLayoutStep .js--select-event-type').dropdown('clear');
  $("#newLayoutStep #preview_image").empty();
  $('#newLayoutStep .js--add-image').show();

  $('#newLayoutStep .step-block').attr('data-actived', 'false');
  $('#newLayoutStep').carousel(0);

  $('#newLayoutModal').bsmodal('hide');
  $('#new_layout .submit-button').html('Create');
  document.getElementById("new_layout").reset();

  new PNotify({
    text: 'Layout <%= @layout.name %> was successfully created',
    addclass: 'notice-success',
    animate: {
      animate: true,
      in_class: 'rotateInDownLeft',
      out_class: 'rotateOutUpRight'
    },
    icon: false
  });
<% else %>
  new PNotify({
    text: 'Something went wrong please try again later',
    addclass: 'notice-error',
    animate: {
      animate: true,
      in_class: 'rotateInDownLeft',
      out_class: 'rotateOutUpRight'
    },
    icon: false
  });
<% end %>

app/views/admins/dashboard/destroy_event_type.js.erb
$('#editEventType<%= @event_type.id %>').bsmodal('hide');

setTimeout(function(){ 
  $('.type-item[data-target="#editEventType<%= @event_type.id %>"]').remove();
  $('#editEventType<%= @event_type.id %>').remove()
}, 500);

app/views/admins/dashboard/edit_layout.html.erb
<div class="admin-main-dashboard">
  <div class="admin-dashboard-screen table-panel">
    <div class="admin-slide-left table-child">
      <%= render "admins/dashboard/dashboard_slide" %>
    </div>
    <div class="dashboard-main table-child">
      <div class="dashboard-layout dashboard-layout-edit">
        <div class="dashboard-header">
          <h2 class="admin-page-title">Edit "<%= @layout.name %>" Layout</h2>
        </div>
        <div class="dashboard-body">
          <%= form_for(@layout, url: admins_update_layout_path(@layout), :remote => true, authenticity_token: true, html: {:multipart => true }) do |f| %>
            <div class="step-body">
              <h4 class="step-title">Step 1: Edit layout information</h4>
              <div class="form-group">
                <h5 class="text-left">Layout name</h5>
                <%= f.text_field :name, class: 'form-control', required: true, placeholder: "Layout name ..." %>
              </div>
              <div class="form-group">
                <h5 class="text-left">Layout types</h5>
                <%= f.select :event_types, @event_types, { :include_blank => "Select type"}, { :multiple => true, :size => 2, :class => "ui fluid search dropdown js--select-event-type semantic-ui-form form-multipe" } %>
                <script type="text/javascript">
                  $('.js--select-event-type').dropdown({
                    maxSelections: 2
                  });
                  <% if @layout.event_types? && @layout.event_types.split(" / ").length != 0 %>
                    <% @layout.event_types.split(" / ").each do |type| %>
                      $('.js--select-event-type').dropdown('set selected', "<%= type %>");
                    <% end %>
                  <% end %>
                </script>
              </div>
              <div class="form-upload-image text-center">
                <h5 class="text-left">Featured Image</h5>
                <label id="layout_featured_image_label" class="cursor-pointer no-outline">
                  <div id="preview_image"></div>
                  <% if @layout.featured_image.blank? %>
                    <img src="<%= asset_url 'add-layout-image.jpg' %>" class="js--add-image add-image-default" >
                  <% else %>
                    <%= cl_image_tag(@layout.featured_image.full_public_id, :transformation=>[{:width=>800, :height=>600, :gravity=>"auto", :crop=>"crop"}, {:width=>400, :height=>300, :crop=>"scale"}], class: "js--add-image add-image-default") %>
                  <% end %>
                  <%= f.file_field :featured_image, class: 'hide' %>
                </label>
              </div>
            </div>
            <div class="step-body">
              <h4 class="step-title">Step 2: Edit HTML code</h4>
              <div class="code-editor-box">
                <%= f.text_area :html, class: 'zevent-code-editor no-outline' %>
              </div>
            </div>
            <div class="step-body">
              <h4 class="step-title">Step 3: Edit CSS code</h4>
              <div class="code-editor-box">
                <%= f.text_area :css, class: 'zevent-code-editor no-outline' %>
              </div>
            </div>
            <div class="step-body">
              <h4 class="step-title">Step 4: Edit Javascript code (Optional)</h4>
              <div class="code-editor-box">
                <%= f.text_area :javascript, class: 'zevent-code-editor no-outline' %>
              </div>
            </div>
            <div class="step-body text-right">
              <%= link_to admins_destroy_layout_path( @layout ), method: :delete, class: 'delete-button btn no-outline' do %>
                Delete
                <i class="fa fa-trash-o" aria-hidden="true"></i>
              <% end %>
              <button type="submit" class="control-button btn no-outline js--submit-edit-layout">
                Update Layout
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  var editorHTML, editorCSS, editorJavascript;

  $("#layout_featured_image").on('change', function () {
    if(typeof (FileReader) != "undefined") {
      var image_holder = $("#preview_image");
      image_holder.empty();
      $('.js--add-image').hide();

      var reader = new FileReader();
      reader.onload = function (e) {
        $("<img />", {
            "src": e.target.result,
            "class": "js--add-image"
        }).appendTo(image_holder);
      }
      
      image_holder.show();
      reader.readAsDataURL($(this)[0].files[0]);
    } else {
      console.log("This browser does not support FileReader.");
    }
  });

  editorHTML = CodeMirror.fromTextArea(document.getElementById("layout_html"), {
    lineNumbers: true,
    styleActiveLine: true,
    matchBrackets: true,
    tabSize: 4,
    mode: 'htmlmixed',
    theme: 'rubyblue',
  });

  editorCSS = CodeMirror.fromTextArea(document.getElementById("layout_css"), {
    lineNumbers: true,
    styleActiveLine: true,
    matchBrackets: true,
    tabSize: 4,
    mode: 'css',
    theme: 'rubyblue',
  });

  editorJavascript = CodeMirror.fromTextArea(document.getElementById("layout_javascript"), {
    lineNumbers: true,
    styleActiveLine: true,
    matchBrackets: true,
    tabSize: 4,
    mode: 'javascript',
    theme: 'rubyblue',
  });

  $('.js--submit-edit-layout').click(function(event) {
    $(this).html('Updating <i class="fa fa-spinner fa-spin" aria-hidden="true"></i>');

    var htmlValue = editorHTML.doc.getValue();
    var cssValue = editorCSS.doc.getValue();
    var javascriptValue = editorJavascript.doc.getValue();

    $('#layout_html').val( htmlValue );
    $('#layout_css').val( cssValue );
    $('#layout_javascript').val( javascriptValue );
  });
</script>

app/views/admins/dashboard/event_type.html.erb
<div class="admin-main-dashboard">
  <div class="admin-dashboard-screen table-panel">
    <div class="admin-slide-left table-child">
      <%= render "admins/dashboard/dashboard_slide" %>
    </div>
    <div class="dashboard-main table-child">
      <div class="dashboard-layout dashboard-event-type">
        <div class="dashboard-header">
          <h2 class="admin-page-title">Event Type</h2>
        </div>
        <div class="dashboard-body">
          <div class="event-type-form">
            <%= form_for(@event_type, url: admins_create_event_type_path, :remote => true, authenticity_token: true) do |f| %>
              <%= f.text_field :label, class: "label-field no-outline", required: true %>
              <%= f.submit "Create", class: "submit-event-type no-outline" %>
            <% end %>
          </div>
          <div class="event-type-list">
            <ul class="list-unstyled list-inline" id="event_type_list">
              <% @event_types.each do |type| %>
                <%= render 'admins/dashboard/event_type_item', type: type %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/dashboard/index.html.erb
<div class="admin-main-dashboard">
  <div class="admin-dashboard-screen table-panel">
    <div class="admin-slide-left table-child">
      <%= render "admins/dashboard/dashboard_slide" %>
    </div>
    <div class="dashboard-main table-child">
      <div class="dashboard-layout dashboard-dashboard">
        <div class="dashboard-header">
          <h2 class="admin-page-title">Dashboard</h2>
        </div>
        <div class="dashboard-body">
          <div class="dashboard-main-item">
            <div class="row">
              <div class="col-md-3">
                <div class="dashboard-item text-center">
                  <h4 class="count"><%= @event_count %></h4> Event created
                </div>
              </div>
              <div class="col-md-3">
                <div class="dashboard-item text-center">
                  <h4 class="count"><%= @user_count %></h4> User sign up
                </div>
              </div>
              <div class="col-md-3">
                <div class="dashboard-item text-center">
                  <h4 class="count"><%= @layout_count %></h4> Themes
                </div>
              </div>
              <div class="col-md-3">
                <div class="dashboard-item text-center">
                  <h4 class="count"><%= @message_count %></h4> Contact Message
                </div>
              </div>
            </div>
          </div>
          <div class="dashboard-analytics">
            <h3 class="dashboard-ana-title">
              Analytics
            </h3>
            <div class="analystic-content">
              <div class="fieldset-1">
                <div class="chart-1">
                  <iframe width="490" height="259" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vSJzHNh4vwxpT_4Ib4YIVVANp7WyYys0_ZFfLmRCrH0TjRFggE4ei8rKRzY6JDdHrl1Y0tDc002cEZD/pubchart?oid=1391189129&amp;format=interactive"></iframe>
                </div>
                <div class="chart-2">
                  <iframe width="490" height="303" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vSJzHNh4vwxpT_4Ib4YIVVANp7WyYys0_ZFfLmRCrH0TjRFggE4ei8rKRzY6JDdHrl1Y0tDc002cEZD/pubchart?oid=2144460812&amp;format=interactive"></iframe>
                </div>
              </div>
              <div class="fieldset-2">
                <div class="chart-3">
                  <iframe width="1010" height="602" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vSJzHNh4vwxpT_4Ib4YIVVANp7WyYys0_ZFfLmRCrH0TjRFggE4ei8rKRzY6JDdHrl1Y0tDc002cEZD/pubchart?oid=1993055154&amp;format=interactive"></iframe>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/dashboard/layout.html.erb
<div class="admin-main-dashboard">
  <div class="admin-dashboard-screen table-panel">
    <div class="admin-slide-left table-child">
      <%= render "admins/dashboard/dashboard_slide" %>
    </div>
    <div class="dashboard-main table-child">
      <div class="dashboard-layout dashboard-layout-list">
        <div class="dashboard-header">
          <h2 class="admin-page-title">Layout</h2>
        </div>
        <div class="dashboard-body">
          <ul class="list-layouts list-unstyled list-inline" id="admins_layout_list">
            <li class="layout-item cursor-pointer" data-toggle="modal" data-target="#newLayoutModal">
              <%= image_tag "add-layout-image.jpg", class: "layout-image" %>
              <div class="layout-text">
                <h4 class="layout-name new-layout">New Layout</h4>
              </div>
            </li>
            <% @layouts.each do |layout| %>
              <%= render "admins/track_layout/layout_item", target_layout: layout %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render 'admins/track_layout/new_layout_modal' %>

app/views/admins/dashboard/messages.html.erb
<div class="admin-main-dashboard">
  <div class="admin-dashboard-screen table-panel">
    <div class="admin-slide-left table-child">
      <%= render "admins/dashboard/dashboard_slide" %>
    </div>
    <div class="dashboard-main table-child">
      <div class="dashboard-layout dashboard-messages">
        <div class="dashboard-header">
          <h2 class="admin-page-title">Contact Messages</h2>
        </div>
        <div class="dashboard-body">
          <div class="message-list">
            <% if @messages.blank? %>
              <div class="text-center no-messages">No contact Messages </div>
            <% else %>
              <ul class="list-unstyled">
                <% @messages.each do |message| %>
                  <%= render 'admins/contact_message/contact_message_item', contact_message: message %>
                <% end %>
              </ul>
            <% end %>
          </div>

          <div class="new-email-block">
            <button type="button" class="new-email-button no-outline" data-toggle="modal" data-target="#newEmailModal"> 
              New Email
              <i class="fa fa-envelope-o" aria-hidden="true"></i>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade zevent-modal" id="newEmailModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <button type="button" class="close-modal no-outline" data-dismiss="modal">
        <%= image_tag "vendor/close.png" %>
      </button>
      <div class="modal-body">
        <h3 class="modal-title">New Email</h3>
        <%= render "admins/contact_message/form_new_email" %>
      </div>
    </div>
  </div>
</div>

app/views/admins/dashboard/new_email.js.erb
<% if @save_success %>
  new PNotify({
    text: 'Email has been success send to <%= @new_message.to_email %>',
    addclass: 'notice-success',
    animate: {
      animate: true,
      in_class: 'rotateInDownLeft',
      out_class: 'rotateOutUpRight'
    },
    icon: false
  });

  $('#newEmailModal #admin_email_to_email').val(''); 
  $('#newEmailModal #admin_email_subject').val('');
  $('#newEmailModal #admin_email_email_body').val('');
<% else %>
  new PNotify({
    text: 'Something went wrong. Please try again later',
    addclass: 'notice-error',
    animate: {
      animate: true,
      in_class: 'rotateInDownLeft',
      out_class: 'rotateOutUpRight'
    },
    icon: false
  });
<% end %>

$('#newEmailModal .js--send-email').html('Send');

app/views/admins/dashboard/reply_messages.js.erb
<% if @save_success %>
  $('#contactMessageModal<%= @reply_messages.message.id %> .js--reply_message_list').prepend('<%= j render "admins/contact_message/reply_message_item", target: @reply_messages %>')
<% end %>

$('#contactMessageModal<%= @reply_messages.message.id %> .js--send-email').html('Send');
$('#contactMessageModal<%= @reply_messages.message.id %> .email_form .label-content').val('');

app/views/admins/dashboard/update_event_type.js.erb
<% if @update_success %>
  $('#editEventType<%= @event_type.id %>').bsmodal('hide');
  $('.type-item[data-target="#editEventType<%= @event_type.id %>"]').text('<%= @event_type.label %>');
<% else %>
  $('#editEventType<%= @event_type.id %>').bsmodal('hide');
  $('#editEventType<%= @event_type.id %> .label-field').val('<%= @event_type.label %>')
<% end %>

app/views/admins/dashboard/update_layout.js.erb
<% if @update_success %>
  new PNotify({
    text: 'Layout was successfully updated',
    addclass: 'notice-success',
    animate: {
      animate: true,
      in_class: 'rotateInDownLeft',
      out_class: 'rotateOutUpRight'
    },
    icon: false
  });
<% else %>
  new PNotify({
    text: 'Something went wrong please try again later',
    addclass: 'notice-error',
    animate: {
      animate: true,
      in_class: 'rotateInDownLeft',
      out_class: 'rotateOutUpRight'
    },
    icon: false
  });
<% end %>
$('.js--submit-edit-layout').html('Update Layout');